# Site settings
title: Federal Website Template

subtitle: 

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

author: "Agency XYZ Staff"

agency: "XYZ Agency"

url: "http://danny8000.github.io" # the base hostname & protocol for your site

timezone: "America/New_York"

exclude: ["README.md", "package.json", "bower.json", "bower_components", "node_modules", "npm-debug.log", "gruntfile.js"]


# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/federal-website-template'

# Build settings
markdown: kramdown

# Kramdown settings
kramdown:
  auto_ids: true
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  parse_block_html: true

excerpt_separator: <!--more-->

# Main Navigation
# List links that should appear in the main navigation (header) here
mainnav:
- text: Home
  url: /
  category: Home
- text: Press releases
  url: /press/
  category: Press
- text: Blog
  url: /blog/
  category: Blog
- text: Publications
  url: /publications/
  category: Publications
- text: Data
  url: /data/
  category: Data
- text: About
  url: /about/
  category: About


# Secondary Navigation
# List links that should appear in the secondary navigation (sidebar) here
secondarynav:
- text: Home
  url: index.html
  internal: true
  category: Overview
- text: About us
  url: about/
  internal: true
  category: About
- text: Accessibity statement
  url: about/accessibility-statement.html
  internal: true
  category: About
- text: Contact us
  url: about/contact-us.html
  internal: true
  category: About
